const pizzasData = {
    "pizza": [
        { "id": 11, "name": "Margherita Pizza", "price": 420, "description": "Pizza Margherita (more commonly known in English as Margherita pizza) is a typical Neapolitan pizza, made with San Marzano tomatoes, mozzarella cheese, fresh basil, salt, and extra-virgin olive oil.", "imageUrl": "margherita.jpg" },
        { "id": 24, "name": "Seafood Pizza", "price": 734, "description": "Seafood pizza is pizza prepared with seafood as a primary ingredient. Many types of seafood ingredients in fresh, frozen or canned forms may be used on seafood pizza.", "imageUrl": "seafood.jpg" },
        { "id": 42, "name": "Chicken Pizza", "price": 440, "description": "An Italian favorite, this chicken pizza recipe is a delicious mix of flat bread or base topped with cheese, chillies, onion, garlic sauce and chunks of chicken.Tossed to perfection, this quick and easy pizza recipe is the solution to all those chicken and cheese cravings. Perfect for those movie nights or parties at home.", "imageUrl": "chicken.jpg" },
        { "id": 65, "name": "Pepproni Pizza", "price": 510, "description": "Pepperoni is an American variety of spicy salami made from cured pork and beef seasoned with paprika or other chili pepper. Prior to cooking, pepperoni is characteristically soft, slightly smoky, and bright red in color. Thinly sliced pepperoni is one of the most popular pizza toppings in American pizzerias. ", "imageUrl": "pepproni.jpg" },
        { "id": 46, "name": "Spinach and Mushroom Pizza", "price": 485, "description": "Simple and delicious but extremely healthy pizza made with mushrooms, garlic and spinach that’s great for a calories conscious person.", "imageUrl": "veggiedeluxe.jpg" },
        { "id": 317, "name": "Mediterranean Pizza", "price": 390, "description": "Mediterranean pizza recipe is the ultimate fresh family dinner that everyone will devour. This is a delicious homemade pizza with tasty Mediterranean toppings that will knock your socks off!", "imageUrl": "medi.png" },
        { "id": 86, "name": "Americano Bacon Pizza", "price": 710, "description": "Bacon is one of those guilty pressures that go well with pretty much anything you put it next to. ", "imageUrl": "american-bacon.jpg" },
        { "id": 19, "name": "Hawaaian Pizza", "price": 300, "description": "Hawaiian pizza or pineapple pizza is a pizza that has pineapple and ham. But, bacon can also be used. It was created in 1962 in Ontario, Canada. This pizza can start arguments, because people debate if pineapple belongs on pizza.", "imageUrl": "hawaiian.jpg" },
        { "id": 54, "name": "Veggie Pizza", "price": 460, "description": "Truly vegan pizza for animal-lovers. It contains made from plants and is 100% cruelty free pizza.", "imageUrl": "vegetable.jpg" }
    ]
}

export default pizzasData;